### ISSUE TITLE
Use lighter weight plotting package

### ISSUE THREAD

**Issue by MilesCranmer** [MilesCranmer/AirspeedVelocity.jl#13]
Plots.jl is extremely heavy-weight, but we only want to create a few line plots. This seems to sometimes result in out-of-memory errors on GitHub actions due to all the artifacts it has to build. Options:

- Gadfly.jl + Cairo.jl. Still requires Cairo (for png export) but there seem to be fewer artifacts compared to Plots.jl
- PlotlyLight.jl + PlotlyKaleido.jl. Probably the lightest option. However seems much less developed as its just a wrapper of Plotly, and my past experiences have been mixed as the docs aren't embedded in Julia.

**Comment by Krastanov** [comment]
an option is to make a couple of recipes for whichever packages you like and then just put them in package extensions (on julia 1.9+). Then the plotting functionality gets loaded only when a plotting library gets loaded.

e.g. `using AirspeedVelocity; using Makie` makes `AirspeedVelocity.airspeedvelocityplot` available; `using AirspeedVelocity; using Plots` makes `Plots.plot(::SomeAirspeedObject)` available, etc. I recently converted one of my projects to that style https://github.com/Krastanov/QuantumClifford.jl/pull/107/files#diff-b88b76a5f384bd43ba78aa7f76ce0ad19af09a9cfa5bce83c02fde8106f08273

**Comment by MilesCranmer** [comment]
Thanks, good idea.

Unfortunately I tried this but it seemed to be overly complicated to have both interfaces as PlotlyLight is a completely different plotting paradigm - basically passing JSONs around which specify a layout, rather than updating a dynamic plot type. Thus I think it might make sense to just take out the Plots.jl code altogether for now.

A plus of this is that PlotlyLight is a thin wrapper of Plotly.js, so it will be much easier to add interactivity later in a web GUI like asv does!

Made a PR in #15.

**Comment by MilesCranmer** [comment]
Side note: it would be cool to upload an interactive HTML page as part of running the benchmarks in a pull request.

For example, ShowYourWork builds a PDF and latexdiff PDF of changes: https://github.com/MilesCranmer/showyourwork_julia_example/pull/1#issuecomment-1509937554

^ It uploads these to a branch with the name `{basebranch}-pdf`.

So perhaps the github action for airspeedvelocity could create a branch `{basebranch}-asv`, and generate an interactive HTML page there. Then, it could provide a link to that page - going to it would load up an interactive Plotly.js plot.

**Comment by MilesCranmer** [comment]
Fixed by #15
