### ISSUE TITLE
How to run on push

### ISSUE THREAD

**Issue by itsdfish** [MilesCranmer/AirspeedVelocity.jl#24]
Hello,

Thank you for this package. I think it is quite useful!

I would like to also run benchmarks after pushing a commit. I tried adding this [line](https://github.com/itsdfish/SequentialSamplingModels.jl/blob/3a1f2b1e361b5fe74c47d9631fe8cd49b87299b0/.github/workflows/benchmark_pr.yml#L7) to the .yml file. It seemed to work except the _find comment_ step did [not work](https://github.com/itsdfish/SequentialSamplingModels.jl/actions/runs/5841315837/job/15841402524).  I have no idea whether this is a related problem, but I am not really sure how to fix it. 

Thanks!

**Comment by MilesCranmer** [comment]
Happy to hear it is useful!

The find comment part is just for PRs. If you are running it on every push, I think you can remove all the commenting functionality. There should be a way to check for if it’s a pull request or not in GitHub actions: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

**Comment by itsdfish** [comment]
Thanks. I think I now see the flaw in what I was doing. Without a PR, there is not a place to write the results.
