### ISSUE TITLE
Benchmarking a (local) dirty state

### ISSUE THREAD

**Issue by maltezfaria** [MilesCranmer/AirspeedVelocity.jl#30]
I wanted to run `benchpkg` in a dirty (local) state of my package, and could not figure out how to do it. 

One workaround is to commit the changes and just pass the appropriate `rev`, but I found that a bit cumbersome when testing ideas that I do not yet want to commit.

I played a bit with the code and found that adding a `dev` option in the CLI to trigger `Pkg.develop(...)` instead of `Pkg.add(...)` inside `_get_script` solved my problem. I was wondering if there is an easy way around that I missed and if not, would this be something that `AirspeedVelocity` may want to support?

Thanks.

**Comment by MilesCranmer** [comment]
Good question. Right now there isn’t; you can only benchmark between commits. But I can totally see how this makes things less convenient so would be supportive of a feature here. I’m not sure how it would work in code though; any ideas?

**Comment by MilesCranmer** [comment]
Maybe using “`dirty`” as a rev would tell it to compare a develop version?

**Comment by maltezfaria** [comment]
I like the idea. So something like this:

```shell
benckpkg --rev=main,dirty
````

would indicate to run on the (possibly) dirty version in `path`? In that case, the `path` argument should be required.

**Comment by MilesCranmer** [comment]
Yeah that sounds good!

**Comment by maltezfaria** [comment]
I will together a PR in the next couple of days then. Thanks.

**Comment by maltezfaria** [comment]
Sorry for taking so long. I opened a draft PR with a (working?) implementation in order to discuss how to go about this.

**Comment by MilesCranmer** [comment]
Yes, thanks!

**Comment by MilesCranmer** [comment]
Closing with #34
