### ISSUE TITLE
--bench-on=dirty

### ISSUE THREAD

**Issue by willow-ahrens** [MilesCranmer/AirspeedVelocity.jl#43]
This one feels like it should work, but I get an error that "dirty" is not a valid revision.

**Comment by MilesCranmer** [comment]
Yeah this would be good as an alias. For right now the solution is to use the `--script` flag explicitly but would be good to have this as a patch

**Comment by willow-ahrens** [comment]
Yes, I just tried this package out yesterday and I agree those would be nice! I was surprised by how many options didn't have defaults.

**Comment by willow-ahrens** [comment]
These convenience features would be much appreciated!
