### ISSUE TITLE
Allow Julia  > 1.8

### ISSUE THREAD

**Issue by itsdfish** [MilesCranmer/AirspeedVelocity.jl#47]
Hello, 

I was wondering whether it is possible to allow newer versions of Julia for benchmarking. I'm guessing there is a reason it is constrained to 1.8, but I am not sure why. 

Thanks.

**Comment by MilesCranmer** [comment]
It does allow it, see https://pkgdocs.julialang.org/v1/compatibility/. 1.8 is the minimum version

**Comment by itsdfish** [comment]
Sorry for the mistake. You are right. 

I was confused by an error in which `stack` was not defined in version 1.8. I incremented to 1.9 on a dev branch and forgot to increment on main. Sorry again for the noise.
